AllCops:
  Exclude:
    - 'Gemfile'
    - 'spec/spec_helper.rb'
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
Metrics/MethodLength:
  CountAsOne: 
    - 'array'

Layout/LineLength:
  Exclude:
    - 'spec/*'
    - 'spec_answers/*'
  